import { ClipboardList, RefreshCw } from "lucide-react"
import { useCallback, useEffect, useState } from "react"
import AdminShell from "@/components/admin/AdminShell"
import { EmptyState, PageHeader, Skeleton, button } from "@/components/campus/ui"
import { getAdminService } from "@/services/adminService"

const pretty = (value) => String(value || "").replaceAll("_", " ").replace(/(^|\s)\S/g, (letter) => letter.toUpperCase())
const formatDate = (value) => new Intl.DateTimeFormat("en-PH", { dateStyle: "medium", timeStyle: "medium" }).format(new Date(value))

export default function AdminAudit() {
  const [rows, setRows] = useState([])
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState("")

  const load = useCallback(async () => {
    setLoading(true)
    setError("")
    try {
      const service = await getAdminService()
      setRows(await service.listAuditActivity())
    } catch (loadError) {
      setError(loadError?.message || "Audit activity could not be loaded.")
    } finally {
      setLoading(false)
    }
  }, [])

  useEffect(() => { load() }, [load])

  return (
    <AdminShell>
      <PageHeader eyebrow="Admin CMS · System" title="Audit Activity" lead="Read-only administrative content events generated by trusted database triggers." actions={<button type="button" onClick={load} disabled={loading} className={button.secondary}><RefreshCw className={`h-4 w-4 ${loading ? "animate-spin" : ""}`} aria-hidden="true" /> Refresh</button>} />

      {error && <div role="alert" className="mt-7 rounded-2xl border border-line-strong bg-surface px-5 py-4 text-sm text-ink">{error}</div>}

      <section aria-label="Audit records" className="mt-5 overflow-hidden rounded-3xl border border-line bg-surface">
        {loading ? <div className="space-y-3 p-5">{[0, 1, 2].map((item) => <Skeleton key={item} className="h-16 w-full" />)}</div> : rows.length ? (
          <div className="overflow-x-auto">
            <table className="w-full min-w-[720px] border-collapse text-left">
              <thead className="border-b border-line bg-subtle text-[10px] font-bold uppercase tracking-[0.12em] text-ink-faint"><tr><th className="px-5 py-3">Actor</th><th className="px-4 py-3">Action</th><th className="px-4 py-3">Entity</th><th className="px-4 py-3">Details</th><th className="px-5 py-3">Timestamp</th></tr></thead>
              <tbody className="divide-y divide-line">
                {rows.map((row) => (
                  <tr key={row.id}><td className="px-5 py-4 text-sm font-medium text-ink">{row.actorName}</td><td className="px-4 py-4 text-xs font-semibold text-ink-mid">{pretty(row.action)}</td><td className="px-4 py-4 text-xs text-ink-mid">{pretty(row.entity_type)} #{row.entity_id}</td><td className="max-w-xs px-4 py-4 text-[11px] text-ink-faint">{pretty(row.metadata?.to_lifecycle || row.metadata?.operation || "Recorded")}</td><td className="px-5 py-4 text-xs text-ink-soft">{formatDate(row.created_at)}</td></tr>
                ))}
              </tbody>
            </table>
          </div>
        ) : <div className="p-5"><EmptyState icon={ClipboardList} title="No audit activity yet" message="Trusted content changes will appear here after the migration is applied." /></div>}
      </section>
    </AdminShell>
  )
}
